### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Guru322** [Th30neAnd0nly/TrackDown#1]
~/TrackDown-1$ npm install
npm: command not installed. Multiple versions of this command were found in Nix.
Select one to run (or press Ctrl-C to cancel):
Adding nodejs-16_x to replit.nix
success
/nix/store/bwxril521b35zlf4x2g32hll64rzfhck-nodejs-16.7.0
npm ERR! code EJSONPARSE
npm ERR! path /home/runner/TrackDown-1/package.json
npm ERR! JSON.parse Unexpected string in JSON at position 204 while parsing '{
npm ERR! JSON.parse   "name": "TrackDown",
npm ERR! JSON.parse   "version": "1'
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

**Comment by prateek-chaubey** [comment]
The issue has been resolved
[commit](https://github.com/Th30neAnd0nly/TrackDown/commit/b1ca5fbea182197b5100a1d304cc1af24f579a34)
