### ISSUE TITLE
Problem page 

### ISSUE THREAD

**Issue by Jriririt** [Th30neAnd0nly/TrackDown#10]
Please page request new page 
![Screenshot_20230312-185948_Chrome](https://user-images.githubusercontent.com/127665015/224547974-2326a6ee-9331-447b-82ed-82153d1cf802.jpg)

2 p
![Screenshot_20230312-190038_Video Player](https://user-images.githubusercontent.com/127665015/224547990-0c86a16e-6b16-4cb1-992e-5823c66c33dc.jpg)
Page 1 problem
Page 2 solve please help 2 page return please help

**Comment by prateek-chaubey** [comment]
Can you elaborate more?
