### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sadicjf7** [Th30neAnd0nly/TrackDown#11]
Not working where to find my
url
![Screenshot_20230316-210841](https://user-images.githubusercontent.com/120778275/225661295-1e9af6aa-5a1e-4c48-b042-1774acabd779.jpg)
![Screenshot_20230316-210853](https://user-images.githubusercontent.com/120778275/225661541-4de00eeb-d2a6-49f9-8afd-2aedd8310cb2.jpg)
![Screenshot_20230316-210901](https://user-images.githubusercontent.com/120778275/225661616-cbbffff5-7a1f-406d-9197-1a3c3421b490.jpg)

**Comment by prateek-chaubey** [comment]
Because you haven't replaced the `repl url`.
> 6.Replace your website URL at index.js

**Comment by sadicjf7** [comment]
> Because you haven't replaced the `repl url`.
> 
> > 6.Replace your website URL at index.js

How how can i get an url

**Comment by prateek-chaubey** [comment]
Watch the video again specially at `01:35`

**Comment by prateek-chaubey** [comment]
I guess not , because if you have followed all the steps correctly then it should have worked. Also do send me the screenshot of your `index.js` file.

**Comment by sadicjf7** [comment]
Ok give me yours talegram link
