### ISSUE TITLE
Not run

### ISSUE THREAD

**Issue by nightlife12** [Th30neAnd0nly/TrackDown#23]
![Screenshot_20230429_233719_Chrome](https://user-images.githubusercontent.com/96279871/235323365-6de3ea6a-440a-4d42-a87b-5b9e4a589f10.jpg)
 I get this issue i doing all like the said. 
![Screenshot_20230429_233719_Chrome](https://user-images.githubusercontent.com/96279871/235323386-1cf87394-84a1-4c6c-9207-8d95ab24de32.jpg)

**Comment by prateek-chaubey** [comment]
You haven't replaced the `YOUR URL` with the url of your repl

**Comment by De-Vo-lab** [comment]
yes same here after replaced with the url

**Comment by prateek-chaubey** [comment]
Clone again and rebuild it , i have patched the issue
