### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by De-Vo-lab** [Th30neAnd0nly/TrackDown#24]
![Screenshot (38)](https://user-images.githubusercontent.com/77851370/235333252-56f5e0eb-5e03-47ce-8664-16ab5ad61d58.png)
![Screenshot (37)](https://user-images.githubusercontent.com/77851370/235333272-20c3294c-5803-46d0-986c-15913ad9e76b.png)

**Comment by De-Vo-lab** [comment]
everything running perfectly but bot not working

**Comment by prateek-chaubey** [comment]
Clone again and rebuild it , i have patched the issue
