### ISSUE TITLE
LINK GENERATED BY MY BOT IS NOT WORKING

### ISSUE THREAD

**Issue by indian-crew** [Th30neAnd0nly/TrackDown#26]
HAVE SETUP EVERYTHING AS VIDEO PROVIDED BY YOU.
But The link generated by my bot is not opening.

It's giving the link like this https://trackdown.icrew2.repl.co/c/2q7k122/aHR0cHM6Ly9pbmRpYW4tY3Jldy5ibG9nc3885C5jb20=

not giving a proper Cloudflare link.

please help bro
![error](https://user-images.githubusercontent.com/105585465/236206269-5ccdbbe4-297d-4324-9dfb-bef8a0de9510.JPG)

**Comment by indian-crew** [comment]
I HAVE SETUP EVERYTHING AS VIDEO PROVIDED BY YOU.
But The link generated by my bot is not opening.

It's giving the link like this https://trackdown.icrew2.repl.co/c/2q7k122/aHR0cHM6Ly9pbmRpYW4tY3Jldy5ibG9nc3885C5jb20=

not giving a proper Cloudflare link.

please help bro

**Comment by prateek-chaubey** [comment]
Seems like and issue with `replit`
Whereas for now use `http` protocol instead of `https` for now.
