### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by itzharshit** [Th30neAnd0nly/TrackDown#45]
Hello i have successfully deployed the bot but the bot is not responding it's reflecting my ip address on `
http://server_ip:5000
` but when i am hitting /start on bot it's not responding.
I have already added my bot token in environment variable by creating .env file in root directory of the bot defined variable as `bot=bot_token_here`

**Comment by prateek-chaubey** [comment]
Try putting it directly in the `index.js` file
Ex:
```js
const bot = new TelegramBot("bot_token", {polling: true});

```

On line 07

**Comment by itzharshit** [comment]
I want to add my domain instead of ip address for url
I have setup the cloudflare as you can see in screenshot but it's not working on the url.

Your guide will be appreciated.

![Screenshot_20231119_132157_Chrome.png](https://github.com/Th30neAnd0nly/TrackDown/assets/87630299/29013fc8-c60d-48e0-b713-465cb6ddbaf5)

**Comment by prateek-chaubey** [comment]
You need to modify the code a bit
On line [239](https://github.com/Th30neAnd0nly/TrackDown/blob/203937ea1e16711ebbff0dc1fb5cca59727f9daf/index.js#L239) modify the port `5000` with port `80`

Like this 
```js
app.listen(80, () => {
```
Afterwards you can rerun the code and then it will show up on `bit.harshit.wtf`.

As mentioned in the readme https://github.com and few other websites may not work in iframe , if they have `x-frame-headers` present
