### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by MN3M1** [Th30neAnd0nly/TrackDown#6]
Camera not working and location
It direct to Desired link automatic and send only device info no location or pics and don't ask for camera permission

**Comment by extr3mna** [comment]
> Camera not working and location
> 
> It direct to Desired link automatic and send only device info no location or pics and don't ask for camera permission 

Good to know!

**Comment by prateek-chaubey** [comment]
Make sure that your browser have respective permissions i.e `camera` and `location`.
Even though your browser have location permission but the `gps` is off then the permission popup won't show up.
